sonar.projectKey=inzamol_qv
sonar.organization=inzamol

# Paths to source directories
sonar.sources=src
sonar.tests=tests

# Exclude example directories, mock projects, and documentation from code quality/security analysis
sonar.exclusions=examples/**,dev_docs/**,docs/**
