"""Central registry of all supported diagnostic rules."""

from __future__ import annotations

from dataclasses import dataclass

from qv.core.models import Severity


@dataclass(frozen=True)
class RuleDefinition:
    """Metadata for a diagnostic rule."""

    id: str
    category: str
    title: str
    description: str
    default_severity: Severity
    remediation_hint: str
    doc_url: str | None = None


DOCS_BASE_URL: str = "https://inzamol.github.io/qv"


def make_doc_url(slug: str) -> str:
    """Construct canonical documentation URL for a rule anchor."""
    return f"{DOCS_BASE_URL}/rules/#{slug}"


# Stable Registry of rules as defined in docs/rules.md
RULES_CATALOG: dict[str, RuleDefinition] = {
    # Dependency rules
    "DEP-001": RuleDefinition(
        id="DEP-001",
        category="dependency",
        title="Dependency constraint conflict",
        description="Two or more declared or transitive dependencies have incompatible version constraints.",
        default_severity=Severity.ERROR,
        remediation_hint="Upgrade the conflicting package or loosen the version pin to satisfy all requirements.",
        doc_url=make_doc_url("11-dep-001-dependency-constraint-conflict"),
    ),
    "DEP-002": RuleDefinition(
        id="DEP-002",
        category="dependency",
        title="Missing dependency declaration",
        description="A third-party package is imported in source code but is not declared in project dependencies.",
        default_severity=Severity.ERROR,
        remediation_hint="Add the missing package to your pyproject.toml or requirements.txt.",
        doc_url=make_doc_url("12-dep-002-missing-dependency-declaration"),
    ),
    "DEP-003": RuleDefinition(
        id="DEP-003",
        category="dependency",
        title="No direct import detected",
        description="A package is declared as a direct dependency, but no direct imports were detected across project source files. This detects the absence of a detected direct import, not proof that the dependency is unused. Dependencies may still be required at runtime through plugins, configuration, framework integration, CLI entrypoints, or indirect mechanisms.",
        default_severity=Severity.WARNING,
        remediation_hint="Verify if this dependency is used dynamically, required as a plugin/driver/runtime configuration, or can be safely removed.",
        doc_url=make_doc_url("13-dep-003-no-direct-import-detected"),
    ),
    "DEP-004": RuleDefinition(
        id="DEP-004",
        category="dependency",
        title="Python compatibility mismatch",
        description="A package requires a Python version incompatible with the target project runtime.",
        default_severity=Severity.WARNING,
        remediation_hint="Update your target Python version or install a version of the package compatible with your Python runtime.",
        doc_url=make_doc_url("14-dep-004-python-compatibility-mismatch"),
    ),
    "DEP-005": RuleDefinition(
        id="DEP-005",
        category="dependency",
        title="Installed/declaration mismatch",
        description="The package version installed in the virtualenv does not match the pinned requirement in project declaration.",
        default_severity=Severity.WARNING,
        remediation_hint="Sync your virtual environment using your package manager (e.g. `uv sync` or `poetry install`).",
        doc_url=make_doc_url("15-dep-005-installeddeclaration-mismatch"),
    ),
    "DEP-006": RuleDefinition(
        id="DEP-006",
        category="dependency",
        title="Vulnerable transitive dependency",
        description="A security vulnerability has been identified in a direct or transitive dependency.",
        default_severity=Severity.ERROR,
        remediation_hint="Update the vulnerable dependency or apply vendor security patches.",
        doc_url=make_doc_url("16-dep-006-vulnerable-transitive-dependency"),
    ),
    # Security rules
    "SEC-001": RuleDefinition(
        id="SEC-001",
        category="security",
        title="Security analysis unavailable",
        description="The advisory database (OSV.dev) could not be reached to perform vulnerability checks.",
        default_severity=Severity.WARNING,
        remediation_hint="Check your internet connection or run with --offline to skip security checks.",
        doc_url=make_doc_url("21-sec-001-security-analysis-unavailable"),
    ),
    # Environment rules
    "ENV-001": RuleDefinition(
        id="ENV-001",
        category="environment",
        title="Python version drift",
        description="The active Python interpreter version differs from the project's target runtime specification.",
        default_severity=Severity.WARNING,
        remediation_hint="Ensure the virtual environment is built using the configured target Python version.",
        doc_url=make_doc_url("31-env-001-python-version-drift"),
    ),
    "ENV-002": RuleDefinition(
        id="ENV-002",
        category="environment",
        title="Docker runtime drift",
        description="The Python version in Dockerfile/docker-compose differs from the project's target runtime.",
        default_severity=Severity.WARNING,
        remediation_hint="Update the base image tag in your Dockerfile to match your project's target Python version.",
        doc_url=make_doc_url("32-env-002-docker-runtime-drift"),
    ),
    "ENV-003": RuleDefinition(
        id="ENV-003",
        category="environment",
        title="CI runtime drift",
        description="CI workflow test matrix does not cover or differs from declared project Python versions.",
        default_severity=Severity.WARNING,
        remediation_hint="Align your CI matrix with the Python versions specified in pyproject.toml.",
        doc_url=make_doc_url("33-env-003-ci-runtime-drift"),
    ),
    # Docker / Container rules
    "DOC-001": RuleDefinition(
        id="DOC-001",
        category="docker",
        title="Inefficient Docker layer caching",
        description="Source code is copied before package dependencies are installed, invalidating the build cache on every code change.",
        default_severity=Severity.WARNING,
        remediation_hint="Copy dependency manifests (e.g. pyproject.toml, requirements.txt) and install packages before copying the full project directory ('COPY . .').",
        doc_url=make_doc_url("81-doc-001-inefficient-docker-layer-caching"),
    ),
    "DOC-002": RuleDefinition(
        id="DOC-002",
        category="docker",
        title="Root user container execution",
        description="The Dockerfile configures an execution entrypoint (CMD/ENTRYPOINT) without specifying a non-root USER.",
        default_severity=Severity.WARNING,
        remediation_hint="Create and switch to a non-privileged user (e.g. 'RUN useradd -m appuser && USER appuser') before the container entrypoint.",
        doc_url=make_doc_url("82-doc-002-root-user-container-execution"),
    ),
    "DOC-003": RuleDefinition(
        id="DOC-003",
        category="docker",
        title="Unpinned base image tag",
        description="The base image uses ':latest' or an unpinned tag, which leads to non-reproducible and unpredictable builds.",
        default_severity=Severity.INFO,
        remediation_hint="Pin the base image to a specific version or hash (e.g. 'python:3.12-slim-bookworm').",
        doc_url=make_doc_url("83-doc-003-unpinned-base-image-tag"),
    ),
    "DOC-004": RuleDefinition(
        id="DOC-004",
        category="docker",
        title="Missing .dockerignore file",
        description="A Dockerfile exists in the project but no .dockerignore file is present, risking baking local virtualenvs, credentials, and temp files into the image.",
        default_severity=Severity.WARNING,
        remediation_hint="Create a .dockerignore file in the repository root excluding .git, .venv, __pycache__, and sensitive files.",
        doc_url=make_doc_url("84-doc-004-missing-dockerignore-file"),
    ),
    "DOC-005": RuleDefinition(
        id="DOC-005",
        category="docker",
        title="Missing --no-cache-dir in pip install",
        description="pip install inside Dockerfile runs without '--no-cache-dir', which unnecessarily bloats the container layer with cached wheels.",
        default_severity=Severity.INFO,
        remediation_hint="Add '--no-cache-dir' to pip install commands (e.g. 'pip install --no-cache-dir -r requirements.txt').",
        doc_url=make_doc_url("85-doc-005-missing-no-cache-dir-in-pip-install"),
    ),
    "DOC-006": RuleDefinition(
        id="DOC-006",
        category="docker",
        title="Sensitive file copied into Docker image",
        description="The Dockerfile explicitly copies sensitive files (.env, private keys, or credentials) into the container image layer.",
        default_severity=Severity.ERROR,
        remediation_hint="Remove sensitive files from COPY instructions and use Docker BuildKit secrets (--mount=type=secret) or runtime environment variables instead.",
        doc_url=make_doc_url("86-doc-006-sensitive-file-copied-into-docker-image"),
    ),
    "DOC-007": RuleDefinition(
        id="DOC-007",
        category="docker",
        title="Missing HEALTHCHECK instruction",
        description="The Dockerfile configures a network service or entrypoint without defining a container HEALTHCHECK.",
        default_severity=Severity.INFO,
        remediation_hint="Add a HEALTHCHECK instruction (e.g. 'HEALTHCHECK --interval=30s CMD curl -f http://localhost:8000/health || exit 1').",
        doc_url=make_doc_url("87-doc-007-missing-healthcheck-instruction"),
    ),
    "DOC-008": RuleDefinition(
        id="DOC-008",
        category="docker",
        title="Missing PYTHONUNBUFFERED=1 environment variable",
        description="Python buffers stdout/stderr by default, which delays or prevents real-time container log streaming.",
        default_severity=Severity.INFO,
        remediation_hint="Add 'ENV PYTHONUNBUFFERED=1' to your Dockerfile to ensure unbuffered real-time log output.",
        doc_url=make_doc_url("88-doc-008-missing-pythonunbuffered-environment-variable"),
    ),
    "DOC-009": RuleDefinition(
        id="DOC-009",
        category="docker",
        title="Deprecated MAINTAINER instruction used",
        description="The MAINTAINER instruction is deprecated in Dockerfile syntax in favor of metadata labels.",
        default_severity=Severity.INFO,
        remediation_hint="Replace 'MAINTAINER <author>' with 'LABEL maintainer=\"<author>\"'.",
        doc_url=make_doc_url("89-doc-009-deprecated-maintainer-instruction-used"),
    ),
    "DOC-010": RuleDefinition(
        id="DOC-010",
        category="docker",
        title="Unnecessary sudo usage in RUN instruction",
        description="Commands in Docker RUN instructions execute with root privileges by default, making 'sudo' redundant and error-prone.",
        default_severity=Severity.WARNING,
        remediation_hint="Remove 'sudo' from RUN instructions during image build.",
        doc_url=make_doc_url("810-doc-010-unnecessary-sudo-usage-in-run-instruction"),
    ),
    "DOC-011": RuleDefinition(
        id="DOC-011",
        category="docker",
        title="apt-get install without cleanup or --no-install-recommends",
        description="apt-get install inside Dockerfile leaves package lists and recommended dependencies in image layers, bloating image size.",
        default_severity=Severity.INFO,
        remediation_hint="Use 'apt-get install -y --no-install-recommends <pkgs> && rm -rf /var/lib/apt/lists/*' in the same RUN layer.",
        doc_url=make_doc_url("811-doc-011-apt-get-install-without-cleanup"),
    ),
    "DOC-012": RuleDefinition(
        id="DOC-012",
        category="docker",
        title="ADD instruction used for local file copy",
        description="The ADD instruction was used to copy local files where COPY is preferred for predictability and security.",
        default_severity=Severity.INFO,
        remediation_hint="Replace 'ADD' with 'COPY' unless automatic tar archive extraction or remote URL fetching is explicitly intended.",
        doc_url=make_doc_url("812-doc-012-add-instruction-used-for-local-file-copy"),
    ),
    "DOC-013": RuleDefinition(
        id="DOC-013",
        category="docker",
        title="Missing PYTHONDONTWRITEBYTECODE=1",
        description="Python creates .pyc bytecode cache files inside container layers that are usually unnecessary in ephemeral containers.",
        default_severity=Severity.INFO,
        remediation_hint="Add 'ENV PYTHONDONTWRITEBYTECODE=1' to prevent writing .pyc files to container filesystem layers.",
        doc_url=make_doc_url("813-doc-013-missing-pythondontwritebytecode"),
    ),
    "DOC-014": RuleDefinition(
        id="DOC-014",
        category="docker",
        title="Web server entrypoint missing EXPOSE instruction",
        description="The container starts a web server but does not declare the listening network port via EXPOSE.",
        default_severity=Severity.INFO,
        remediation_hint="Add 'EXPOSE <port>' (e.g. 'EXPOSE 8000') to document the port on which the container listens.",
        doc_url=make_doc_url("814-doc-014-web-server-entrypoint-missing-expose"),
    ),
    # Import / Architecture rules
    "IMP-001": RuleDefinition(
        id="IMP-001",
        category="architecture",
        title="Circular import detected",
        description="An import cycle exists between two or more modules, which may cause runtime initialization errors.",
        default_severity=Severity.ERROR,
        remediation_hint="Refactor shared dependencies into a separate module or use deferred/lazy imports.",
        doc_url=make_doc_url("41-imp-001-circular-import-detected"),
    ),
    "IMP-002": RuleDefinition(
        id="IMP-002",
        category="architecture",
        title="Unresolved local import",
        description="A local module imported in source code could not be resolved on the project's Python path.",
        default_severity=Severity.ERROR,
        remediation_hint="Verify the module name and ensure source directory is marked on the PYTHONPATH or package root.",
        doc_url=make_doc_url("42-imp-002-unresolved-local-import"),
    ),
    "IMP-003": RuleDefinition(
        id="IMP-003",
        category="architecture",
        title="Unused / orphan local module",
        description="A Python source file exists in the project but is never imported or referenced by any other module, entry point, or test file.",
        default_severity=Severity.WARNING,
        remediation_hint="Review if this module is obsolete and can be safely deleted or integrated into your package exports.",
        doc_url=make_doc_url("43-imp-003-unused-orphan-local-module"),
    ),
    "IMP-004": RuleDefinition(
        id="IMP-004",
        category="compatibility",
        title="Deprecated or removed standard library module",
        description="A standard library module imported in source code was deprecated or completely removed in modern Python (PEP 594).",
        default_severity=Severity.ERROR,
        remediation_hint="Replace the removed stdlib module with its modern replacement (e.g. importlib instead of imp, subprocess instead of pipes).",
        doc_url=make_doc_url("44-imp-004-deprecated-or-removed-standard-library-module"),
    ),
    # Packaging rules
    "PKG-001": RuleDefinition(
        id="PKG-001",
        category="packaging",
        title="Missing package metadata",
        description="Essential packaging metadata (such as project name, version, or description) is missing.",
        default_severity=Severity.WARNING,
        remediation_hint="Provide project name and version in pyproject.toml [project] table.",
        doc_url=make_doc_url("51-pkg-001-missing-package-metadata"),
    ),
    "PKG-002": RuleDefinition(
        id="PKG-002",
        category="packaging",
        title="Invalid project configuration",
        description="The project configuration file contains syntax errors or invalid keys.",
        default_severity=Severity.ERROR,
        remediation_hint="Fix configuration syntax to conform to PEP 621 / tool specifications.",
        doc_url=make_doc_url("52-pkg-002-invalid-project-configuration"),
    ),
    # FastAPI Framework rules (FAP-xxx)
    "FAP-001": RuleDefinition(
        id="FAP-001",
        category="framework",
        title="Blocking call or CPU-bound operation in async endpoint",
        description="Synchronous blocking operations (e.g. time.sleep, requests, subprocess, synchronous DB queries) or CPU-bound hashing called inside an async def FastAPI route handler block the asyncio event loop.",
        default_severity=Severity.ERROR,
        remediation_hint="Use non-blocking async alternatives (e.g. asyncio.sleep, httpx.AsyncClient) or run blocking/CPU calls in worker threads via anyio.to_thread.run_sync or fastapi.concurrency.run_in_threadpool.",
        doc_url=make_doc_url("61-fap-001-blocking-call-or-cpu-bound-operation-in-async-endpoint"),
    ),
    "FAP-002": RuleDefinition(
        id="FAP-002",
        category="framework",
        title="Blocking dependency in async path",
        description="An async route handler depends on a dependency (via Depends) that executes blocking synchronous I/O or CPU operations.",
        default_severity=Severity.WARNING,
        remediation_hint="Refactor dependency to use async operations or execute in a worker threadpool.",
        doc_url=make_doc_url("62-fap-002-blocking-dependency-in-async-path"),
    ),
    "FAP-003": RuleDefinition(
        id="FAP-003",
        category="framework",
        title="Missing response model or return type annotation",
        description="FastAPI route endpoint does not declare a response_model argument or return type annotation, disabling schema validation and response serialization.",
        default_severity=Severity.WARNING,
        remediation_hint="Add a return type annotation (-> ResponseModel) or pass response_model to the route decorator.",
        doc_url=make_doc_url("63-fap-003-missing-response-model-or-return-type-annotation"),
    ),
    "FAP-004": RuleDefinition(
        id="FAP-004",
        category="framework",
        title="Insecure CORS or debug configuration",
        description="CORSMiddleware configured with allow_origins=['*'] and allow_credentials=True, or FastAPI instantiated with debug=True.",
        default_severity=Severity.ERROR,
        remediation_hint="Specify explicit trusted origins in allow_origins when credentials are enabled, and disable debug mode in production.",
        doc_url=make_doc_url("64-fap-004-insecure-cors-or-debug-configuration"),
    ),
    "FAP-005": RuleDefinition(
        id="FAP-005",
        category="framework",
        title="Missing HTTP client timeout configuration",
        description="HTTP client (such as httpx.AsyncClient, httpx.Client, or aiohttp.ClientSession) instantiated without an explicit timeout.",
        default_severity=Severity.WARNING,
        remediation_hint="Configure an explicit timeout (e.g. timeout=10.0) to prevent hanging connections.",
        doc_url=make_doc_url("65-fap-005-missing-http-client-timeout-configuration"),
    ),
    "FAP-006": RuleDefinition(
        id="FAP-006",
        category="framework",
        title="Route path parameter template mismatch",
        description="A path parameter defined in the route URL template (e.g. '/users/{user_id}') does not match any parameter in the handler function signature.",
        default_severity=Severity.ERROR,
        remediation_hint="Ensure all {param} placeholders in route URL decorators match parameter names in the endpoint function signature.",
        doc_url=make_doc_url("66-fap-006-route-path-parameter-template-mismatch"),
    ),
    "FAP-007": RuleDefinition(
        id="FAP-007",
        category="framework",
        title="Unsafe yield dependency without try/finally",
        description="A generator dependency using yield does not wrap cleanup code in a try...finally block, causing resource and connection leaks on exceptions.",
        default_severity=Severity.WARNING,
        remediation_hint="Wrap the yield and teardown logic in a try...finally block to guarantee resource cleanup.",
        doc_url=make_doc_url("67-fap-007-unsafe-yield-dependency-without-tryfinally"),
    ),
    "FAP-008": RuleDefinition(
        id="FAP-008",
        category="framework",
        title="Deprecated @app.on_event lifecycle hook",
        description="Using deprecated @app.on_event('startup' / 'shutdown') handlers instead of modern lifespan context managers.",
        default_severity=Severity.WARNING,
        remediation_hint="Migrate @app.on_event to '@asynccontextmanager async def lifespan(app: FastAPI)' and pass to FastAPI(lifespan=lifespan).",
        doc_url=make_doc_url("68-fap-008-deprecated-appon_event-lifecycle-hook"),
    ),
    "FAP-009": RuleDefinition(
        id="FAP-009",
        category="framework",
        title="Untyped or unvalidated request body",
        description="Route handler accepts a raw 'dict', 'Any', or untyped Body parameter instead of a Pydantic model, bypassing automatic request validation.",
        default_severity=Severity.WARNING,
        remediation_hint="Define a Pydantic BaseModel schema for the request payload to ensure type safety and validation.",
        doc_url=make_doc_url("69-fap-009-untyped-or-unvalidated-request-body"),
    ),
    "FAP-010": RuleDefinition(
        id="FAP-010",
        category="framework",
        title="Shadowed or duplicate route endpoint",
        description="Multiple route handlers are registered with the identical HTTP method and path on the same app/router, causing one to shadow the other.",
        default_severity=Severity.ERROR,
        remediation_hint="Ensure all routes have unique method and path combinations, or combine related logic into a single handler.",
        doc_url=make_doc_url("610-fap-010-shadowed-or-duplicate-route-endpoint"),
    ),
    "FAP-011": RuleDefinition(
        id="FAP-011",
        category="framework",
        title="Mutable default value in route parameter",
        description="Route handler uses a mutable default argument (e.g. list or dict), which can leak state across concurrent requests.",
        default_severity=Severity.WARNING,
        remediation_hint="Use None as default (e.g. filters: list[str] | None = None) or use Field(default_factory=list).",
        doc_url=make_doc_url("611-fap-011-mutable-default-value-in-route-parameter"),
    ),
    "FAP-012": RuleDefinition(
        id="FAP-012",
        category="framework",
        title="Invalid exception handler signature",
        description="Custom @app.exception_handler function does not take the required (request, exc) parameters, causing runtime crashes.",
        default_severity=Severity.ERROR,
        remediation_hint="Ensure custom exception handlers accept exactly two parameters: '(request: Request, exc: Exception)'.",
        doc_url=make_doc_url("612-fap-012-invalid-exception-handler-signature"),
    ),
    "FAP-013": RuleDefinition(
        id="FAP-013",
        category="framework",
        title="Untracked asyncio.create_task in route handler",
        description="Spawning raw asyncio.create_task inside route handlers without background task management can cause lost exceptions and unhandled crashes.",
        default_severity=Severity.WARNING,
        remediation_hint="Use FastAPI's built-in BackgroundTasks ('background_tasks.add_task(...)') for request-scoped background jobs.",
        doc_url=make_doc_url("613-fap-013-untracked-asynciocreate_task-in-route-handler"),
    ),
    "FAP-014": RuleDefinition(
        id="FAP-014",
        category="framework",
        title="Potential path traversal in FileResponse",
        description="FileResponse initialized directly with an unvalidated path variable from route parameters, risking arbitrary file read vulnerabilities.",
        default_severity=Severity.WARNING,
        remediation_hint="Validate and resolve the file path against a trusted base directory before passing to FileResponse.",
        doc_url=make_doc_url("614-fap-014-potential-path-traversal-in-fileresponse"),
    ),
    "FAP-015": RuleDefinition(
        id="FAP-015",
        category="framework",
        title="Blocking file I/O in async endpoint",
        description="Using synchronous open() or blocking file read/write operations inside an async def route handler blocks the event loop.",
        default_severity=Severity.ERROR,
        remediation_hint="Use 'aiofiles', 'anyio.Path', or run file I/O in a synchronous def route handler.",
        doc_url=make_doc_url("615-fap-015-blocking-file-io-in-async-endpoint"),
    ),
    "FAP-016": RuleDefinition(
        id="FAP-016",
        category="framework",
        title="Sensitive field exposure in schema",
        description="Pydantic model schema exposes sensitive password/secret fields without Field(exclude=True) or response filtering.",
        default_severity=Severity.ERROR,
        remediation_hint="Mark sensitive fields with 'Field(exclude=True)' or create a separate output schema (e.g. UserResponse).",
        doc_url=make_doc_url("616-fap-016-sensitive-field-exposure-in-schema"),
    ),
    "FAP-017": RuleDefinition(
        id="FAP-017",
        category="framework",
        title="Non-standard HTTP status code on POST or DELETE",
        description="Mutation routes (POST/DELETE) return default 200 OK instead of standard REST status codes (201 Created or 204 No Content).",
        default_severity=Severity.WARNING,
        remediation_hint="Specify status_code=status.HTTP_201_CREATED on POST routes or status.HTTP_204_NO_CONTENT on DELETE routes.",
        doc_url=make_doc_url("617-fap-017-non-standard-http-status-code-on-post-or-delete"),
    ),
    "FAP-018": RuleDefinition(
        id="FAP-018",
        category="framework",
        title="Global in-memory state mutation in route handler",
        description="Route handler mutates global/module-level collections or variables without synchronization locks, causing concurrency bugs.",
        default_severity=Severity.ERROR,
        remediation_hint="Use a proper database, Redis cache, or an asyncio.Lock for shared state.",
        doc_url=make_doc_url("618-fap-018-global-in-memory-state-mutation-in-route-handler"),
    ),
    "FAP-019": RuleDefinition(
        id="FAP-019",
        category="framework",
        title="Insecure cookie configuration",
        description="response.set_cookie() called without httponly=True or secure=True flags, exposing cookies to XSS or network interception.",
        default_severity=Severity.ERROR,
        remediation_hint="Set 'httponly=True' and 'secure=True' when storing sensitive session or auth cookies.",
        doc_url=make_doc_url("619-fap-019-insecure-cookie-configuration"),
    ),
    "FAP-020": RuleDefinition(
        id="FAP-020",
        category="framework",
        title="Potential open redirect in RedirectResponse",
        description="RedirectResponse initialized directly with user-supplied URL parameter without domain whitelist validation.",
        default_severity=Severity.WARNING,
        remediation_hint="Validate that the redirect target is a relative path or matches an allowed domain whitelist.",
        doc_url=make_doc_url("620-fap-020-potential-open-redirect-in-redirectresponse"),
    ),
    "FAP-021": RuleDefinition(
        id="FAP-021",
        category="framework",
        title="Router included without tags or prefix",
        description="app.include_router() called without 'tags' or 'prefix', leading to unorganized OpenAPI documentation and URL clashes.",
        default_severity=Severity.WARNING,
        remediation_hint="Provide 'prefix' and 'tags' when including routers (e.g. app.include_router(user_router, prefix='/users', tags=['Users'])).",
        doc_url=make_doc_url("621-fap-021-router-included-without-tags-or-prefix"),
    ),
    "FAP-022": RuleDefinition(
        id="FAP-022",
        category="framework",
        title="WebSocket route missing await websocket.accept()",
        description="WebSocket endpoint sends or receives data before calling 'await websocket.accept()', which causes runtime errors.",
        default_severity=Severity.ERROR,
        remediation_hint="Call 'await websocket.accept()' before reading or writing data to the WebSocket.",
        doc_url=make_doc_url("622-fap-022-websocket-route-missing-await-websocketaccept"),
    ),
    "FAP-023": RuleDefinition(
        id="FAP-023",
        category="framework",
        title="Deprecated Pydantic v1 Config class",
        description="Pydantic schema uses deprecated inner 'class Config:' instead of Pydantic v2 'model_config = ConfigDict(...)'.",
        default_severity=Severity.WARNING,
        remediation_hint="Migrate inner 'class Config:' to 'model_config = ConfigDict(...)'.",
        doc_url=make_doc_url("623-fap-023-deprecated-pydantic-v1-config-class"),
    ),
    "FAP-024": RuleDefinition(
        id="FAP-024",
        category="framework",
        title="Redundant duplicate dependency declaration",
        description="Route handler declares multiple parameters resolving the exact same dependency callable.",
        default_severity=Severity.WARNING,
        remediation_hint="Consolidate duplicate dependencies into a single parameter.",
        doc_url=make_doc_url("624-fap-024-redundant-duplicate-dependency-declaration"),
    ),
    "FAP-025": RuleDefinition(
        id="FAP-025",
        category="framework",
        title="Returned HTTPException instance instead of raise",
        description="Returning an HTTPException instance in a route handler returns a 200 OK HTTP response with the serialized exception object instead of raising an error.",
        default_severity=Severity.ERROR,
        remediation_hint="Use 'raise HTTPException(...)' instead of 'return HTTPException(...)'.",
        doc_url=make_doc_url("625-fap-025-returned-httpexception-instance-instead-of-raise"),
    ),
    "FAP-026": RuleDefinition(
        id="FAP-026",
        category="framework",
        title="Deprecated Pydantic v1 @validator or @root_validator",
        description="Using deprecated Pydantic v1 '@validator' or '@root_validator' decorators instead of Pydantic v2 '@field_validator' or '@model_validator'.",
        default_severity=Severity.WARNING,
        remediation_hint="Migrate to '@field_validator' or '@model_validator' from pydantic.",
        doc_url=make_doc_url("626-fap-026-deprecated-pydantic-v1-validator-or-root_validator"),
    ),
    "FAP-027": RuleDefinition(
        id="FAP-027",
        category="framework",
        title="Dependency parameter missing type annotation",
        description="Route parameter initialized with 'Depends(...)', 'Query(...)', or 'Path(...)' does not specify a type annotation, disabling FastAPI schema generation and static type checking.",
        default_severity=Severity.WARNING,
        remediation_hint="Add explicit type annotation: 'param: Type = Depends(...)' or 'param: Annotated[Type, Depends(...)]'.",
        doc_url=make_doc_url("627-fap-027-dependency-parameter-missing-type-annotation"),
    ),
    "FAP-028": RuleDefinition(
        id="FAP-028",
        category="framework",
        title="Raw json.loads called on request body",
        description="Calling 'json.loads(await request.body())' or 'json.loads(request.body)' is an anti-pattern; FastAPI and Starlette provide an optimized built-in 'await request.json()' method.",
        default_severity=Severity.WARNING,
        remediation_hint="Replace 'json.loads(await request.body())' with 'await request.json()'.",
        doc_url=make_doc_url("628-fap-028-raw-jsonloads-called-on-request-body"),
    ),
    "FAP-029": RuleDefinition(
        id="FAP-029",
        category="framework",
        title="StreamingResponse initialized without media_type",
        description="Instantiating StreamingResponse without specifying 'media_type' can cause clients to misinterpret the streamed content format.",
        default_severity=Severity.WARNING,
        remediation_hint="Pass an explicit media_type argument (e.g. StreamingResponse(stream, media_type='application/json')).",
        doc_url=make_doc_url("629-fap-029-streamingresponse-initialized-without-media_type"),
    ),
    "FAP-030": RuleDefinition(
        id="FAP-030",
        category="framework",
        title="Missing route summary or docstring for OpenAPI documentation",
        description="Public route endpoint does not provide a docstring, 'summary', or 'description', resulting in sparse and incomplete OpenAPI documentation.",
        default_severity=Severity.WARNING,
        remediation_hint="Add a function docstring or pass 'summary=...' in the route decorator.",
        doc_url=make_doc_url(
            "630-fap-030-missing-route-summary-or-docstring-for-openapi-documentation"
        ),
    ),
    "FAP-031": RuleDefinition(
        id="FAP-031",
        category="framework",
        title="Prefer typing.Annotated over parameter default assignment",
        description="FastAPI strongly recommends using standard typing.Annotated[Type, Depends(...)] instead of parameter default values for cleaner typing and reusable dependencies.",
        default_severity=Severity.INFO,
        remediation_hint="Refactor parameter to 'param: Annotated[Type, Depends(...)]' or 'param: Annotated[Type, Query(...)]'.",
        doc_url=make_doc_url(
            "631-fap-031-prefer-typingannotated-over-parameter-default-assignment"
        ),
    ),
    "FAP-032": RuleDefinition(
        id="FAP-032",
        category="framework",
        title="Redundant jsonable_encoder with response_model",
        description="Calling jsonable_encoder() inside a route handler that already declares response_model causes double serialization, reducing throughput.",
        default_severity=Severity.WARNING,
        remediation_hint="Return raw objects or dicts directly and let FastAPI's response_model handle serialization.",
        doc_url=make_doc_url("632-fap-032-redundant-jsonable_encoder-with-response_model"),
    ),
    "FAP-033": RuleDefinition(
        id="FAP-033",
        category="framework",
        title="Missing from_attributes=True in ORM response schema",
        description="Pydantic response model for ORM/database objects is missing 'model_config = ConfigDict(from_attributes=True)', causing validation failures when serializing ORM instances.",
        default_severity=Severity.WARNING,
        remediation_hint="Add 'model_config = ConfigDict(from_attributes=True)' to the Pydantic schema.",
        doc_url=make_doc_url("633-fap-033-missing-from_attributestrue-in-orm-response-schema"),
    ),
    "FAP-034": RuleDefinition(
        id="FAP-034",
        category="framework",
        title="Missing await on request.json() or request.body()",
        description="Calling request.json() or request.body() without 'await' inside an async def route handler assigns an un-awaited coroutine instead of parsed data.",
        default_severity=Severity.ERROR,
        remediation_hint="Add 'await' before 'request.json()' or 'request.body()'.",
        doc_url=make_doc_url("634-fap-034-missing-await-on-requestjson-or-requestbody"),
    ),
    "FAP-035": RuleDefinition(
        id="FAP-035",
        category="framework",
        title="Raw Exception raised instead of HTTPException",
        description="Raising generic Exception, ValueError, or RuntimeError in route handlers triggers uncaught 500 Internal Server Errors instead of structured REST HTTP error responses.",
        default_severity=Severity.WARNING,
        remediation_hint="Raise 'HTTPException(status_code=..., detail=...)' for predictable API client error responses.",
        doc_url=make_doc_url("635-fap-035-raw-exception-raised-instead-of-httpexception"),
    ),
    "FAP-036": RuleDefinition(
        id="FAP-036",
        category="framework",
        title="Mutating app.state inside route handler",
        description="Mutating request.app.state or app.state inside per-request route handlers introduces concurrency race conditions. Application state should be initialized in lifespan context managers.",
        default_severity=Severity.WARNING,
        remediation_hint="Initialize shared state in the lifespan context manager before startup rather than modifying app.state in route handlers.",
        doc_url=make_doc_url("636-fap-036-mutating-appstate-inside-route-handler"),
    ),
    "FAP-037": RuleDefinition(
        id="FAP-037",
        category="framework",
        title="SecurityScopes declared with Depends instead of Security",
        description="SecurityScopes parameter declared in a dependency using Depends(...) will not receive requested scopes. Use Security(dependency, scopes=[...]) instead.",
        default_severity=Severity.WARNING,
        remediation_hint="Use 'Security(dependency, scopes=[...])' when protecting endpoints with OAuth2 SecurityScopes.",
        doc_url=make_doc_url(
            "637-fap-037-securityscopes-declared-with-depends-instead-of-security"
        ),
    ),
    "FAP-038": RuleDefinition(
        id="FAP-038",
        category="framework",
        title="Hardcoded HTTP status code integer",
        description="Using integer literals for status_code (e.g. status_code=201) reduces readability compared to named constants like status.HTTP_201_CREATED.",
        default_severity=Severity.INFO,
        remediation_hint="Import status from fastapi (or HTTPStatus from http) and use named constants (e.g. status.HTTP_201_CREATED).",
        doc_url=make_doc_url("638-fap-038-hardcoded-http-status-code-integer"),
    ),
    # SQLAlchemy & SQL Framework rules (SQL-xxx)
    "SQL-001": RuleDefinition(
        id="SQL-001",
        category="framework",
        title="Potential N+1 database query in loop",
        description="Executing database queries (session.execute, session.query, session.get, or select()) inside for/while loops causes N+1 performance degradation.",
        default_severity=Severity.WARNING,
        remediation_hint="Batch query objects using 'select(...).where(Model.id.in_(ids))' or eager relationship options (e.g. joinedload/selectinload).",
        doc_url=make_doc_url("71-sql-001-potential-n1-database-query-in-loop"),
    ),
    "SQL-002": RuleDefinition(
        id="SQL-002",
        category="framework",
        title="Session instantiated without context manager or cleanup",
        description="Instantiating a Session without a with-statement context manager or try...finally session.close() causes database connection pool exhaustion.",
        default_severity=Severity.WARNING,
        remediation_hint="Use 'with SessionLocal() as session:' or wrap session lifecycle in a context manager / dependency yield.",
        doc_url=make_doc_url("72-sql-002-session-instantiated-without-context-manager-or-cleanup"),
    ),
    "SQL-003": RuleDefinition(
        id="SQL-003",
        category="framework",
        title="Synchronous DB operation in async event loop",
        description="Invoking synchronous database engine calls or synchronous session operations inside an async def function blocks the asyncio event loop.",
        default_severity=Severity.ERROR,
        remediation_hint="Use SQLAlchemy async extension ('create_async_engine' and 'AsyncSession') with async drivers (e.g. asyncpg, aiosqlite).",
        doc_url=make_doc_url("73-sql-003-synchronous-db-operation-in-async-event-loop"),
    ),
    "SQL-004": RuleDefinition(
        id="SQL-004",
        category="framework",
        title="Raw SQL string interpolation (SQL Injection Risk)",
        description="Constructing SQL queries using f-strings or string formatting with text() or cursor.execute() introduces severe SQL injection vulnerabilities.",
        default_severity=Severity.ERROR,
        remediation_hint="Use bound query parameters with text('SELECT ... WHERE id = :id'), {'id': user_val}.",
        doc_url=make_doc_url("74-sql-004-raw-sql-string-interpolation-sql-injection-risk"),
    ),
    "SQL-005": RuleDefinition(
        id="SQL-005",
        category="framework",
        title="Legacy SQLAlchemy 1.x session.query() syntax",
        description="Using legacy session.query(...) instead of modern SQLAlchemy 2.0 select() and session.scalars().",
        default_severity=Severity.WARNING,
        remediation_hint="Migrate from 'session.query(User).filter(...)' to 'session.scalars(select(User).where(...))'.",
        doc_url=make_doc_url("75-sql-005-legacy-sqlalchemy-1x-sessionquery-syntax"),
    ),
    "SQL-006": RuleDefinition(
        id="SQL-006",
        category="framework",
        title="Missing relationship eager loading strategy in async session",
        description="Accessing lazy-loaded ORM relationships without explicit joinedload/selectinload in async sessions triggers MissingGreenlet errors.",
        default_severity=Severity.WARNING,
        remediation_hint="Specify 'options(selectinload(Model.relation))' or set lazy='selectin' on relationship definition.",
        doc_url=make_doc_url(
            "76-sql-006-missing-relationship-eager-loading-strategy-in-async-session"
        ),
    ),
    "SQL-007": RuleDefinition(
        id="SQL-007",
        category="framework",
        title="Uncommitted transaction in mutation function",
        description="Session performs mutations (session.add / session.delete) but never executes session.commit() or enters a transaction with session.begin().",
        default_severity=Severity.WARNING,
        remediation_hint="Ensure mutations are committed with 'await session.commit()' or executed inside 'with session.begin():'.",
        doc_url=make_doc_url("77-sql-007-uncommitted-transaction-in-mutation-function"),
    ),
    "SQL-008": RuleDefinition(
        id="SQL-008",
        category="framework",
        title="create_engine missing pool_pre_ping connection health check",
        description="Creating a database engine without 'pool_pre_ping=True' can lead to runtime disconnect errors when idle connections are closed by firewalls/servers.",
        default_severity=Severity.WARNING,
        remediation_hint="Add 'pool_pre_ping=True' to create_engine() / create_async_engine().",
        doc_url=make_doc_url(
            "78-sql-008-create_engine-missing-pool_pre_ping-connection-health-check"
        ),
    ),
    "SQL-009": RuleDefinition(
        id="SQL-009",
        category="framework",
        title="expire_on_commit=True in AsyncSession",
        description="Configuring AsyncSession or async_sessionmaker with expire_on_commit=True (the default) causes MissingGreenlet exceptions when accessing committed model attributes.",
        default_severity=Severity.WARNING,
        remediation_hint="Set 'expire_on_commit=False' when instantiating AsyncSession or async_sessionmaker.",
        doc_url=make_doc_url("79-sql-009-expire_on_committrue-in-asyncsession"),
    ),
    "SQL-010": RuleDefinition(
        id="SQL-010",
        category="framework",
        title="Hardcoded database credentials in connection URL",
        description="Database URL contains plain-text passwords or secret credentials in source code instead of loading from environment variables.",
        default_severity=Severity.ERROR,
        remediation_hint="Read database connection strings from environment variables (e.g. os.getenv('DATABASE_URL')).",
        doc_url=make_doc_url("710-sql-010-hardcoded-database-credentials-in-connection-url"),
    ),
    "SQL-011": RuleDefinition(
        id="SQL-011",
        category="framework",
        title="Unbounded SELECT query without limit or pagination",
        description="Calling .all() on queries against database tables without limit() or pagination clauses risks memory exhaustion on large datasets.",
        default_severity=Severity.WARNING,
        remediation_hint="Add '.limit(limit)' and pagination parameters to query statements.",
        doc_url=make_doc_url("711-sql-011-unbounded-select-query-without-limit-or-pagination"),
    ),
    "SQL-012": RuleDefinition(
        id="SQL-012",
        category="framework",
        title="Relationship cascade delete without ForeignKey ondelete CASCADE",
        description="Configuring relationship cascade='all, delete-orphan' without database-level ondelete='CASCADE' on ForeignKey forces slow Python-side row-by-row deletion.",
        default_severity=Severity.INFO,
        remediation_hint="Add ondelete='CASCADE' to ForeignKey and passive_deletes=True to relationship for database-level cascading.",
        doc_url=make_doc_url(
            "712-sql-012-relationship-cascade-delete-without-foreignkey-ondelete-cascade"
        ),
    ),
    "SQL-013": RuleDefinition(
        id="SQL-013",
        category="framework",
        title="Session flush or commit called inside loop",
        description="Calling session.flush() or session.commit() inside loops creates high database roundtrip overhead. Use bulk insert or single commit after loop.",
        default_severity=Severity.WARNING,
        remediation_hint="Move session.commit() outside the loop or use session.execute(insert(Model), batch_data).",
        doc_url=make_doc_url("713-sql-013-session-flush-or-commit-called-inside-loop"),
    ),
    "SQL-014": RuleDefinition(
        id="SQL-014",
        category="framework",
        title="Deprecated declarative_base() function",
        description="Using legacy declarative_base() instead of modern SQLAlchemy 2.0 class Base(DeclarativeBase): pass.",
        default_severity=Severity.WARNING,
        remediation_hint="Define 'class Base(DeclarativeBase): pass' from sqlalchemy.orm.",
        doc_url=make_doc_url("714-sql-014-deprecated-declarative_base-function"),
    ),
    "SQL-015": RuleDefinition(
        id="SQL-015",
        category="framework",
        title="SQLite engine missing check_same_thread=False in multi-threaded application",
        description="SQLite engine initialized without connect_args={'check_same_thread': False} can cause ProgrammingError in multi-threaded web applications.",
        default_severity=Severity.WARNING,
        remediation_hint="Pass connect_args={'check_same_thread': False} to create_engine() when using SQLite in web applications.",
        doc_url=make_doc_url(
            "715-sql-015-sqlite-engine-missing-check_same_threadfalse-in-multi-threaded-application"
        ),
    ),
    "SQL-016": RuleDefinition(
        id="SQL-016",
        category="framework",
        title="Missing database migration configuration (Alembic)",
        description="SQLAlchemy database models are defined in the project, but no Alembic migrations directory or alembic.ini configuration exists.",
        default_severity=Severity.INFO,
        remediation_hint="Initialize database migrations using 'alembic init alembic'.",
        doc_url=make_doc_url("716-sql-016-missing-database-migration-configuration-alembic"),
    ),
    "SQL-017": RuleDefinition(
        id="SQL-017",
        category="framework",
        title="Mapped[...] attribute missing mapped_column() in 2.0 Declarative Model",
        description="Using legacy Column() or raw field assignment with Mapped[...] type annotations instead of SQLAlchemy 2.0's native mapped_column().",
        default_severity=Severity.WARNING,
        remediation_hint="Replace 'col: Mapped[int] = Column(Integer)' with 'col: Mapped[int] = mapped_column()'.",
        doc_url=make_doc_url(
            "717-sql-017-mapped-attribute-missing-mapped_column-in-20-declarative-model"
        ),
    ),
    "SQL-018": RuleDefinition(
        id="SQL-018",
        category="framework",
        title="Excessive connection pool size in single application instance",
        description="create_engine configured with pool_size or max_overflow > 50 in a single instance, risking database connection exhaustion.",
        default_severity=Severity.WARNING,
        remediation_hint="Keep pool_size between 5 and 20 per instance and use external connection poolers (e.g. pgBouncer) for scaling.",
        doc_url=make_doc_url(
            "718-sql-018-excessive-connection-pool-size-in-single-application-instance"
        ),
    ),
    "SQL-019": RuleDefinition(
        id="SQL-019",
        category="framework",
        title="NullPool configured in persistent web application",
        description="Using NullPool in persistent web servers disables connection pooling and creates high latency TCP connection overhead on every request.",
        default_severity=Severity.WARNING,
        remediation_hint="Use default QueuePool or AsyncAdaptedQueuePool for persistent web applications; reserve NullPool for AWS Lambda/serverless.",
        doc_url=make_doc_url("719-sql-019-nullpool-configured-in-persistent-web-application"),
    ),
    "SQL-020": RuleDefinition(
        id="SQL-020",
        category="framework",
        title="Declarative ORM Model missing primary key definition",
        description="Declarative ORM model defined without at least one primary key column (primary_key=True), which will cause runtime ORM mapping failures.",
        default_severity=Severity.ERROR,
        remediation_hint="Define at least one column with 'primary_key=True' or 'mapped_column(primary_key=True)'.",
        doc_url=make_doc_url("720-sql-020-declarative-orm-model-missing-primary-key-definition"),
    ),
    "SQL-021": RuleDefinition(
        id="SQL-021",
        category="framework",
        title="Missing session.rollback() in database exception handler",
        description="Catching exceptions around database queries/mutations without invoking session.rollback() leaves the session in an unusable invalid state.",
        default_severity=Severity.WARNING,
        remediation_hint="Add 'session.rollback()' in exception handlers or use 'with session.begin():' for automatic rollback on error.",
        doc_url=make_doc_url("721-sql-021-missing-sessionrollback-in-database-exception-handler"),
    ),
    "SQL-022": RuleDefinition(
        id="SQL-022",
        category="framework",
        title="Large binary or heavy text column without deferred/load_only strategy",
        description="Model includes LargeBinary or Large Text column without deferred() loading, causing heavy memory consumption during full-table selects.",
        default_severity=Severity.INFO,
        remediation_hint="Wrap large blob/text columns with 'deferred(Column(LargeBinary))' or use select(Model).options(load_only(...)).",
        doc_url=make_doc_url(
            "722-sql-022-large-binary-or-heavy-text-column-without-deferredload_only-strategy"
        ),
    ),
    "SQL-023": RuleDefinition(
        id="SQL-023",
        category="framework",
        title="ForeignKey column defined without index=True",
        description="ForeignKey column created without index=True, causing expensive sequential scans during joins, foreign key lookups, and cascade operations.",
        default_severity=Severity.WARNING,
        remediation_hint="Add 'index=True' to ForeignKey column definitions (e.g. Column(Integer, ForeignKey('users.id'), index=True)).",
        doc_url=make_doc_url("723-sql-023-foreignkey-column-defined-without-indextrue"),
    ),
    "SQL-024": RuleDefinition(
        id="SQL-024",
        category="framework",
        title="Insecure unencrypted remote database connection URL",
        description="Remote database connection URL targeting external hosts does not specify sslmode=require or ssl=true.",
        default_severity=Severity.WARNING,
        remediation_hint="Append '?sslmode=require' (PostgreSQL) or '?ssl=true' to production database connection strings.",
        doc_url=make_doc_url("724-sql-024-insecure-unencrypted-remote-database-connection-url"),
    ),
    "SQL-025": RuleDefinition(
        id="SQL-025",
        category="framework",
        title="Deprecated engine.execute() or engine.scalar() direct call",
        description="Calling engine.execute() or engine.scalar() directly is removed in SQLAlchemy 2.0.",
        default_severity=Severity.ERROR,
        remediation_hint="Use explicit connection contexts: 'with engine.connect() as conn: result = conn.execute(stmt)'.",
        doc_url=make_doc_url("725-sql-025-deprecated-engineexecute-or-enginescalar-direct-call"),
    ),
    "SQL-026": RuleDefinition(
        id="SQL-026",
        category="framework",
        title="AsyncSession instantiated without async context manager or await close()",
        description="AsyncSession created without 'async with' context manager or explicit 'await session.close()', causing connection leaks in async tasks.",
        default_severity=Severity.WARNING,
        remediation_hint="Use 'async with AsyncSessionLocal() as session:' or ensure 'await session.close()' in a finally block.",
        doc_url=make_doc_url(
            "726-sql-026-asyncsession-instantiated-without-async-context-manager-or-await-close"
        ),
    ),
    "SQL-027": RuleDefinition(
        id="SQL-027",
        category="framework",
        title="Unsafe concurrent numeric balance or counter update without with_for_update()",
        description="Querying a record and updating numeric counters or balance fields without row-level locking (with_for_update()) causes lost update race conditions.",
        default_severity=Severity.WARNING,
        remediation_hint="Lock rows with 'select(...).with_for_update()' or use atomic SQL increments 'update(Account).values(balance=Account.balance - amt)'.",
        doc_url=make_doc_url(
            "727-sql-027-unsafe-concurrent-numeric-balance-or-counter-update-without-with_for_update"
        ),
    ),
    "SQL-028": RuleDefinition(
        id="SQL-028",
        category="framework",
        title="Thread-local scoped_session used in async context",
        description="Using thread-local scoped_session in async applications causes session sharing across coroutines and race conditions.",
        default_severity=Severity.ERROR,
        remediation_hint="Use async_scoped_session(..., scopefunc=asyncio.current_task) or dependency injection per request.",
        doc_url=make_doc_url("728-sql-028-thread-local-scoped_session-used-in-async-context"),
    ),
    "SQL-029": RuleDefinition(
        id="SQL-029",
        category="framework",
        title="Declarative ORM model missing __tablename__ definition",
        description="Declarative model inheriting from Base/DeclarativeBase does not define __tablename__ or __table__, causing mapping errors.",
        default_severity=Severity.ERROR,
        remediation_hint="Define '__tablename__ = \"table_name\"' on concrete ORM classes (or set '__abstract__ = True' for mixins).",
        doc_url=make_doc_url("729-sql-029-declarative-orm-model-missing-tablename-definition"),
    ),
    "SQL-030": RuleDefinition(
        id="SQL-030",
        category="framework",
        title="Direct DBAPI raw_connection() used without cleanup",
        description="Calling engine.raw_connection() bypasses connection pool management and leaks connections if not closed explicitly.",
        default_severity=Severity.WARNING,
        remediation_hint="Always close raw DBAPI connections in a try...finally block: 'raw_conn = engine.raw_connection(); try: ... finally: raw_conn.close()'.",
        doc_url=make_doc_url("730-sql-030-direct-dbapi-raw_connection-used-without-cleanup"),
    ),
    # CI/CD Workflow rules
    "CI-001": RuleDefinition(
        id="CI-001",
        category="ci",
        title="CI Python matrix version mismatch",
        description="CI workflow tests Python versions incompatible with declared project requires-python or classifiers.",
        default_severity=Severity.WARNING,
        remediation_hint="Align CI test matrix versions with supported project Python ranges.",
        doc_url=make_doc_url("111-ci-001-ci-python-matrix-version-mismatch"),
    ),
    "CI-002": RuleDefinition(
        id="CI-002",
        category="ci",
        title="Unfrozen dependency installation in CI",
        description="CI workflow installs dependencies without lockfiles or hash verification.",
        default_severity=Severity.WARNING,
        remediation_hint="Use lockfiles (e.g. 'uv sync --frozen', 'poetry install --sync', or 'pip-sync') in CI workflows.",
        doc_url=make_doc_url("112-ci-002-unfrozen-dependency-installation-in-ci"),
    ),
    "CI-003": RuleDefinition(
        id="CI-003",
        category="ci",
        title="Deprecated or outdated CI action version",
        description="Workflow references a deprecated or end-of-life GitHub Actions version.",
        default_severity=Severity.INFO,
        remediation_hint="Upgrade GitHub Actions to current stable major releases (e.g. actions/checkout@v4).",
        doc_url=make_doc_url("113-ci-003-deprecated-or-outdated-ci-action-version"),
    ),
    "CI-004": RuleDefinition(
        id="CI-004",
        category="ci",
        title="Missing test or quality gate in CI workflow",
        description="Pull request / push workflow contains no test suite, linter, or health checks.",
        default_severity=Severity.INFO,
        remediation_hint="Add automated test or lint steps (e.g. pytest, ruff, qv scan --ci).",
        doc_url=make_doc_url("114-ci-004-missing-test-or-quality-gate-in-ci-workflow"),
    ),
    "CI-005": RuleDefinition(
        id="CI-005",
        category="ci",
        title="Insecure secret or token in CI workflow",
        description="Potential plaintext secret or token literal detected in workflow file.",
        default_severity=Severity.ERROR,
        remediation_hint="Store credentials in repository secrets (${{ secrets.MY_SECRET }}).",
        doc_url=make_doc_url("115-ci-005-insecure-secret-or-token-in-ci-workflow"),
    ),
    "CI-006": RuleDefinition(
        id="CI-006",
        category="ci",
        title="Missing concurrency cancellation in PR workflow",
        description="Pull request workflow lacks concurrency cancellation, causing redundant runner minutes.",
        default_severity=Severity.INFO,
        remediation_hint="Add concurrency group with 'cancel-in-progress: true'.",
        doc_url=make_doc_url("116-ci-006-missing-concurrency-cancellation-in-pr-workflow"),
    ),
    # Django Framework rules (DJG-xxx)
    "DJG-001": RuleDefinition(
        id="DJG-001",
        category="framework",
        title="Insecure hardcoded DEBUG = True in Django settings",
        description="Django settings hardcodes 'DEBUG = True' without environment variable fallback, risking sensitive traceback exposure.",
        default_severity=Severity.ERROR,
        remediation_hint="Load DEBUG dynamically from an environment variable: os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'.",
        doc_url=make_doc_url("121-djg-001-insecure-hardcoded-debug-true-in-django-settings"),
    ),
    "DJG-002": RuleDefinition(
        id="DJG-002",
        category="framework",
        title="Hardcoded SECRET_KEY in Django settings",
        description="Hardcoded SECRET_KEY literal detected in settings. Secrets must be loaded from environment variables.",
        default_severity=Severity.ERROR,
        remediation_hint="Load SECRET_KEY from environment: os.environ['DJANGO_SECRET_KEY'].",
        doc_url=make_doc_url("122-djg-002-hardcoded-secret_key-in-django-settings"),
    ),
    "DJG-003": RuleDefinition(
        id="DJG-003",
        category="framework",
        title="Insecure wildcard ALLOWED_HOSTS in Django settings",
        description="ALLOWED_HOSTS contains wildcard '*' allowing Host header poisoning.",
        default_severity=Severity.WARNING,
        remediation_hint="Explicitly define allowed domain names or load from environment.",
        doc_url=make_doc_url("123-djg-003-insecure-wildcard-allowed_hosts-in-django-settings"),
    ),
    "DJG-004": RuleDefinition(
        id="DJG-004",
        category="framework",
        title="Potential N+1 database query in loop",
        description="QuerySet execution inside loop causes N+1 query overhead.",
        default_severity=Severity.WARNING,
        remediation_hint="Prefetch related relations before looping: queryset.prefetch_related('...').",
        doc_url=make_doc_url("124-djg-004-potential-n1-database-query-in-loop"),
    ),
    "DJG-005": RuleDefinition(
        id="DJG-005",
        category="framework",
        title="Django ForeignKey missing explicit on_delete",
        description="models.ForeignKey declared without required 'on_delete' argument.",
        default_severity=Severity.WARNING,
        remediation_hint="Specify explicit on_delete behavior: models.CASCADE, models.PROTECT, or models.SET_NULL.",
        doc_url=make_doc_url("125-djg-005-django-foreignkey-missing-explicit-on_delete"),
    ),
    "DJG-006": RuleDefinition(
        id="DJG-006",
        category="framework",
        title="Missing CSRF Protection Middleware",
        description="MIDDLEWARE list is missing 'django.middleware.csrf.CsrfViewMiddleware'.",
        default_severity=Severity.WARNING,
        remediation_hint="Add 'django.middleware.csrf.CsrfViewMiddleware' to MIDDLEWARE.",
        doc_url=make_doc_url("126-djg-006-missing-csrf-protection-middleware"),
    ),
    # Celery Framework rules (CEL-xxx)
    "CEL-001": RuleDefinition(
        id="CEL-001",
        category="framework",
        title="Insecure Celery pickle serializer enabled",
        description="Celery serializer setting uses 'pickle', allowing arbitrary code execution if brokers are compromised.",
        default_severity=Severity.ERROR,
        remediation_hint="Use secure serialization formats like 'json' or 'msgpack'.",
        doc_url=make_doc_url("131-cel-001-insecure-celery-pickle-serializer-enabled"),
    ),
    "CEL-002": RuleDefinition(
        id="CEL-002",
        category="framework",
        title="Missing task timeout limits in Celery task",
        description="Celery task has no 'time_limit' or 'soft_time_limit' configured.",
        default_severity=Severity.WARNING,
        remediation_hint="Specify 'time_limit' and 'soft_time_limit' on task decorator: @shared_task(time_limit=300, soft_time_limit=240).",
        doc_url=make_doc_url("132-cel-002-missing-task-timeout-limits-in-celery-task"),
    ),
    "CEL-003": RuleDefinition(
        id="CEL-003",
        category="framework",
        title="Unbounded retry policy on Celery task",
        description="Celery task permits unlimited retries, risking broker congestion.",
        default_severity=Severity.WARNING,
        remediation_hint="Set explicit 'max_retries' (e.g. max_retries=3, default_retry_delay=60).",
        doc_url=make_doc_url("133-cel-003-unbounded-retry-policy-on-celery-task"),
    ),
    "CEL-004": RuleDefinition(
        id="CEL-004",
        category="framework",
        title="Blocking time.sleep() in asynchronous Celery task",
        description="Async Celery task invokes 'time.sleep()', blocking the async event loop.",
        default_severity=Severity.WARNING,
        remediation_hint="Use 'await asyncio.sleep()' instead of 'time.sleep()'.",
        doc_url=make_doc_url("134-cel-004-blocking-timesleep-in-asynchronous-celery-task"),
    ),
    # Engine execution rules
    "ENG-001": RuleDefinition(
        id="ENG-001",
        category="engine",
        title="Analyzer execution failed",
        description="An analyzer raised an unexpected exception during execution.",
        default_severity=Severity.ERROR,
        remediation_hint="Check the error message or report a bug to the analyzer maintainer.",
        doc_url=make_doc_url("91-eng-001-analyzer-execution-failed"),
    ),
    # Project discovery rules
    "DISC-001": RuleDefinition(
        id="DISC-001",
        category="discovery",
        title="Unreadable source file",
        description="A source file could not be read during project discovery due to permissions or encoding errors.",
        default_severity=Severity.WARNING,
        remediation_hint="Check file read permissions and ensure file is encoded in valid UTF-8.",
        doc_url=make_doc_url("101-disc-001-unreadable-source-file"),
    ),
    "DISC-002": RuleDefinition(
        id="DISC-002",
        category="discovery",
        title="Python syntax error in source file",
        description="A Python source file contains invalid syntax and could not be parsed into an AST.",
        default_severity=Severity.WARNING,
        remediation_hint="Fix the syntax error in the source file.",
        doc_url=make_doc_url("102-disc-002-python-syntax-error-in-source-file"),
    ),
}


def get_rule_definition(rule_id: str) -> RuleDefinition | None:
    """Retrieve rule definition by ID."""
    return RULES_CATALOG.get(rule_id.upper())
